"""Add is_active and credit_limit to wallets

Revision ID: 38b3f14e370d
Revises: cbc807782163
Create Date: 2026-03-31 03:10:32.361720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b3f14e370d'
down_revision: Union[str, Sequence[str], None] = 'cbc807782163'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('wallets', sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'credit_limit')
    op.drop_column('wallets', 'is_active')
    # ### end Alembic commands ###
