"""Add quantity to investments

Revision ID: 5e1bfba0d1e8
Revises: 79aee8821840
Create Date: 2026-04-12 03:19:33.854328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e1bfba0d1e8'
down_revision: Union[str, Sequence[str], None] = '79aee8821840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments', sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investments', 'quantity')
    # ### end Alembic commands ###
