"""add is_rollover to budgets

Revision ID: ba3e26a24f84
Revises: 59ad80630598
Create Date: 2026-03-29 03:13:40.783432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3e26a24f84'
down_revision: Union[str, Sequence[str], None] = '59ad80630598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('is_rollover', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'is_rollover')
    # ### end Alembic commands ###
