"""Add total_passive_income to investments

Revision ID: cbc807782163
Revises: f7703a8b0f47
Create Date: 2026-03-30 03:49:38.257794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc807782163'
down_revision: Union[str, Sequence[str], None] = 'f7703a8b0f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investments', sa.Column('total_passive_income', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investments', 'total_passive_income')
    # ### end Alembic commands ###
